name: Build Windows Electron App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm install

      - run: npm run dist:win

      - uses: actions/upload-artifact@v4
        with:
          name: Sticker-Zone
          path: |
            dist/*.exe
            dist/*.msi
            dist/*.zip
            dist/win-unpacked/**